# Generated by Django 4.1.3 on 2022-11-29 09:35

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('descprition', models.TextField()),
                ('category', models.IntegerField(choices=[(0, 'Photographic products'), (1, 'Writing Tools')])),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Invaild Email')])),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'manager'), (1, 'worker'), (2, 'Customer')], default=3)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='newInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dt', models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 35, 40, 785764))),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.user')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='amount must be greater than 0')])),
                ('available', models.IntegerField(default=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='amount must be greater than 0')]))),
                ('serial', models.IntegerField(default=0, unique=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.locations')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products')),
            ],
        ),
    ]
