# Generated by Django 4.0 on 2022-12-08 23:02

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='amount must be greater than 0')])),
                ('available', models.IntegerField(default=-1)),
                ('serial', models.IntegerField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='locations',
            fields=[
                ('location', models.CharField(max_length=6, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2022, 12, 9, 1, 2, 49, 626940))),
                ('return_date', models.DateTimeField(default=datetime.datetime(2022, 12, 29, 1, 2, 49, 626940))),
                ('status', models.IntegerField(choices=[(0, 'waiting'), (1, 'completed'), (2, 'collected')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('sku', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField()),
                ('descprition', models.TextField()),
                ('category', models.IntegerField(choices=[(0, 'Photographic products'), (1, 'Writing Tools')])),
                ('serial_item', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')])),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True, validators=[django.core.validators.EmailValidator(message='Invaild Email')])),
                ('name', models.CharField(max_length=50)),
                ('role', models.IntegerField(choices=[(0, 'manager'), (1, 'worker'), (2, 'student')], default=2)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='specific_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='amount must be greater than 0')])),
                ('completed', models.BooleanField(default=False)),
                ('inventory_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.inventory')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.orders')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.products')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.user'),
        ),
        migrations.CreateModel(
            name='newInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('dt', models.DateTimeField(default=datetime.datetime(2022, 12, 9, 1, 2, 49, 611241))),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.products')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.user')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.locations'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.products'),
        ),
    ]
