# Generated by Django 4.1.3 on 2022-11-29 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_newinventory_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='serial_item',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newinventory',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 11, 41, 45, 556462)),
        ),
    ]
