# Generated by Django 4.1.3 on 2022-12-01 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_products_serial_item_alter_newinventory_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='available',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial',
            field=models.IntegerField(default=None, unique=True),
        ),
        migrations.AlterField(
            model_name='newinventory',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 1, 17, 21, 7, 699433)),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(0, 'manager'), (1, 'worker'), (2, 'Customer')], default=2),
        ),
    ]
