# Generated by Django 4.0 on 2022-12-07 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_orders_alter_inventory_serial_alter_newinventory_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='serial',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newinventory',
            name='dt',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 39, 55, 817382)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 12, 39, 55, 817382)),
        ),
        migrations.AlterField(
            model_name='orders',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 27, 12, 39, 55, 817382)),
        ),
    ]
